### ISSUE TITLE
It doesn't work with 7tsp icons!

### ISSUE THREAD

**Issue by RedDragonTix** [ramensoftware/resource-redirect-icon-themes#3]
Hi, I'm trying to change icons to XP ones with Resource Direct mod instead of using 7tsp! I've got XP 7tsp icons from WinClassic, I have extracted resources from the 7tsp archive and then put it into resource redirect directory! Created theme.ini and Resources folder, changed from dll.mun.res to .dll files! putting the redirections, applying and it's still the default!

then I tried with dll.mun, doesn't work! Putting the redirections manually on Windhawk settings, doesn't work, refreshing icon cache doesn't work neither, even with folder thumbnail remover!

I've tried a different iconpack from your repository, in this case Sweet-Rainbow, and it seems it works!

then I must do something wrong?

here's my theme.ini:

[redirections]
%SystemRoot%\System32\imageres.dll=.\Windhawk Resources\imageres.dll
%SystemRoot%\System32\shell32.dll=.\Windhawk Resources\shell32.dll
%SystemRoot%\System32\zipfldr.dll=.\Windhawk Resources\zipfldr.dll

**Comment by m417z** [comment]
How did you create the dll files, such as `.\Windhawk Resources\imageres.dll`? Can you post them here? They must be dll files (not .res, for example, so if you're using Resource Hacker, save as dll), and the resource ids must match those your system uses.

**Comment by RedDragonTix** [comment]
> How did you create the dll files, such as `.\Windhawk Resources\imageres.dll`? Can you post them here? They must be dll files (not .res, for example, so if you're using Resource Hacker, save as dll), and the resource ids must match those your system uses.

well all I did was extract the resources files from 7tsp archive, then rename the .res files to .dll
maybe I could try saving the .res to .dll with Resource Hacker

**Comment by RedDragonTix** [comment]
It actually works with resource hacker! not renaming it, thank you!

**Comment by m417z** [comment]
Great! If you create/port new icon themes, consider submitting them here to this repository.

**Comment by okamitime** [comment]
How would we go about changing the extensions to .dll when there are files that share similar names, for example basebrd.dll.mun and basebrd.dll.mui? I'm also wondering how you would change .cpl or .exe files to work with this mod.

**Comment by m417z** [comment]
@okamitime

> How would we go about changing the extensions to .dll when there are files that share similar names, for example basebrd.dll.mun and basebrd.dll.mui?

In this case, you only need to redirect `basebrd.dll`. `.mun` and `.mui` are like Windows built-in redirections for the main file.

> I'm also wondering how you would change .cpl or .exe files to work with this mod.

In the same way. The redirection file can be either .cpl/.exe or .dll, as long as it contains the resources to be used.
