### ISSUE TITLE
Converting 7TSP themes

### ISSUE THREAD

**Issue by SandTechStuff** [ramensoftware/resource-redirect-icon-themes#4]
Sorry if this is an improper place to talk about this, but discussions are not enabled,

7TSP icon themes come with files with the ".res" and ".mun" file extensions in front of the original filename. If you rename them to get rid of these extensions, they have no icons inside that Windows can find (tested by using the dll in the change icon prompt for shortcuts).

The themes provided in this repo are 7TSP themes, yet have files with normal ".dll" or ".exe" extensions. They also have icons that Windows can detect (using the same method). How do you convert 7TSP icon themes to work with resource redirect?

**Comment by m417z** [comment]
Hi, it was discussed recently here: https://github.com/ramensoftware/resource-redirect-icon-themes/issues/3#issuecomment-2308412669.

Perhaps I need to add it to the readme.

Let me know if you need more information.

**Comment by SandTechStuff** [comment]
I didn't think to check closed issues, sorry about that. 🤦

Looks like I just need to export with Resource Hacker.
